name = "gr8r-youtube-worker"
main = "src/index.js"
compatibility_date = "2025-09-24"
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[observability.logs]
enabled = true

[[queues.consumers]]
queue = "pub-youtube-q"
max_batch_size = 5
max_batch_timeout = 5

[vars]
REQUIRE_FUTURE_SCHEDULE = "1"

[[services]]
binding = "DB1"
service  = "gr8r-db1-worker"

[[secrets_store_secrets]]
binding     = "DB1_INTERNAL_KEY"
store_id    = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "DB1_INTERNAL_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_USER"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_USER"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_URL"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_URL"

[[secrets_store_secrets]]
binding     = "YOUTUBE_CLIENT_ID"
store_id    = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "YOUTUBE_CLIENT_ID"

[[secrets_store_secrets]]
binding     = "YOUTUBE_CLIENT_SECRET"
store_id    = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "YOUTUBE_CLIENT_SECRET"

[[secrets_store_secrets]]
binding     = "YOUTUBE_REFRESH_TOKEN"
store_id    = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "YOUTUBE_REFRESH_TOKEN"

[triggers]
crons = ["*/10 * * * *"]
