name = "gr8r-revai-callback-worker"
main = "src/index.js"
compatibility_date = "2025-06-24"
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "videos-gr8r"

[[services]]
binding = "SOCIALCOPY_WORKER"
service = "gr8r-socialcopy-worker"

[[services]]
binding = "REVAIFETCH"
service = "gr8r-revai-worker"

[[services]]
binding = "AIRTABLE"
service = "gr8r-airtable-worker"

[[services]]
binding = "ASSETS"
service = "gr8r-assets-worker"

[[services]]
binding = "DB1"
service = "gr8r-db1-worker"

[[secrets_store_secrets]]
binding = "DB1_INTERNAL_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "DB1_INTERNAL_KEY"

[[secrets_store_secrets]]
binding = "INTERNAL_WORKER_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "INTERNAL_WORKER_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_USER"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_USER"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_URL"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_URL"

[[routes]]
pattern = "callback.gr8r.com/*"
zone_name = "gr8r.com"
