name = "gr8r-orch-pub-worker"
main = "src/index.js"
compatibility_date = "2025-07-25"
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"
workers_dev = false

routes = [
  { pattern = "api.gr8r.com/orch*",  zone_name = "gr8r.com" },
 ]

[observability]
enabled = true

[[services]]
binding = "DB1"
service = "gr8r-db1-worker"
entrypoint = "fetch"

[[secrets_store_secrets]]
binding = "DB1_INTERNAL_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "DB1_INTERNAL_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_USER"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_USER"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_URL"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_URL"

# Producer → YouTube queue (must exist)
[[queues.producers]]
binding = "PUB_YOUTUBE_Q"
queue = "pub-youtube-q"

