name = "gr8r-r2sign-worker"
main = "src/index.js"                  # CHANGED: bundle directly from source
compatibility_date = "2025-07-11"
node_compat = true                     # ADDED: needed for @aws-sdk on Workers
workers_dev = false
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[observability.logs]
enabled = true                         # keep CF Observability enabled

[[routes]]
pattern = "r2sign.gr8r.com/*"
zone_name = "gr8r.com"

[[services]]
binding = "GRAFANA_WORKER"
service = "gr8r-grafana-worker"

