name = "gr8r-r2sign-worker"
main = "src/index.js"                  # CHANGED: bundle directly from source
compatibility_date = "2025-07-11"
compatibility_flags = ["nodejs_compat"]                  # ADDED: needed for @aws-sdk on Workers
workers_dev = false
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[observability.logs]
enabled = true                         # keep CF Observability enabled

[[routes]]
pattern = "r2sign.gr8r.com/*"
zone_name = "gr8r.com"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_KEY"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_USER"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_USER"

[[secrets_store_secrets]]
binding = "GRAFANACLOUD_GR8R_LOGS_URL"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "GRAFANACLOUD_GR8R_LOGS_URL"

[[secrets_store_secrets]]
binding = "R2_ACCOUNT_ID"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "R2_ACCOUNT_ID"

[[secrets_store_secrets]]
binding = "R2_ACCESS_KEY_ID"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "R2_ACCESS_KEY_ID"

[[secrets_store_secrets]]
binding = "R2_SECRET_ACCESS_KEY"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "R2_SECRET_ACCESS_KEY"

