name = "gr8r-grafana-worker"
main = "index.js"
compatibility_date = "2025-06-12"
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[[routes]]
pattern = "api.gr8r.com/api/grafana"
zone_name = "gr8r.com"
