name = "gr8r-grafana-worker"
main = "src/index.js"
compatibility_date = "2025-06-12"
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[[routes]]
pattern = "api.gr8r.com/api/grafana"
zone_name = "gr8r.com"

[[secrets_store_secrets]]
binding = "ADMIN_TOKEN"
store_id = "23d622f0d3b8499fa021fad6149af8c9"
secret_name = "ADMIN_TOKEN"