name = "gr8terthings-forms"           # ← purely for human referencecd 

# This tells Wrangler where to find the output directory for Pages deploys
pages_build_output_dir = "."

# Optional now — becomes useful later if you use functions/
compatibility_date = "2025-07-26"

[env.production]
# You can define bindings here later if needed #
