name: Reusable Worker Deployment

on:
  workflow_call:
    inputs:
      workingDirectory:
        required: true
        type: string
      workerName:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ inputs.workerName }} to Cloudflare

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log context
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Deploying ${{ inputs.workerName }} Worker..."

      - name: Set up Node & install Wrangler
        run: npm install -g wrangler@4.26.0

      - name: Deploy Worker with Wrangler
        working-directory: ${{ inputs.workingDirectory }}
        run: wrangler deploy --log-level debug
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Dump directory contents (on failure)
        if: failure()
        run: |
          echo "Listing contents of ${{ inputs.workingDirectory }}:"
          ls -la ${{ inputs.workingDirectory }}
          echo "--- wrangler.toml ---"
          cat ${{ inputs.workingDirectory }}/wrangler.toml || echo "Missing wrangler.toml"
