name: Global Worker deploy

on:
  workflow_call:
    inputs:
      workingDirectory:
        required: true
        type: string
      workerName:
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ inputs.workerName }} to Cloudflare

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log context
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Deploying ${{ inputs.workerName }} Worker..."
          echo "Using config: ${{ inputs.workingDirectory }}/wrangler.toml"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install repo deps (pinned wrangler)
        run: npm ci

      - name: Deploy Worker with Wrangler (repo-pinned via npx)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler deploy --config "${{ inputs.workingDirectory }}/wrangler.toml"

      - name: Dump directory contents (on failure)
        if: failure()
        run: |
          echo "Listing contents of ${{ inputs.workingDirectory }}:"
          ls -la "${{ inputs.workingDirectory }}"
          echo "--- wrangler.toml ---"
          cat "${{ inputs.workingDirectory }}/wrangler.toml" || echo "Missing wrangler.toml"

      - name: Output Wrangler error log (on failure)
        if: failure()
        run: |
          echo "--- Wrangler Error Log ---"
          cat ~/.config/.wrangler/logs/*.log || echo "No logs found"
