name: Deploy subscribe-worker

on:
  push:
    paths:
      - 'workers/subscribe-worker/**'
      - '.github/workflows/deploy-subscribe-worker.yml'
      - '.github/workflows/_deploy-worker.yml'   # ← Add this

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-worker.yml
    with:
      workingDirectory: workers/subscribe-worker
      workerName: subscribe
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
