name: Deploy videosdb1 Worker

on:
  push:
    paths:
      - 'workers/videosdb1/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy videosdb1 to Cloudflare
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: workers/videosdb1
          command: publish --verbose
